"""
Agentic Report Generator using ReAct-style reasoning.
Session 9: Agents and Tool Use (perceive -> reason -> act -> observe).
Session 11: Claude Code workflow engineering.
"""
import json
from typing import Dict, List
from report_engine.rag_engine import LiteratureRAG


class PopulationReportAgent:
    """
    A minimal ReAct agent that:
    1. Perceives model prediction + quality audit + region metadata
    2. Reasons about what evidence is needed
    3. Acts by retrieving literature (Tool: RAG)
    4. Observes and synthesizes a final markdown report
    """
    def __init__(self, rag: LiteratureRAG = None):
        self.rag = rag or LiteratureRAG()

    def generate_report(
        self,
        region_name: str,
        predicted_pop: float,
        confidence: str,
        quality_scorecard: Dict,
        year: int,
    ) -> str:
        """
        ReAct loop simplified into a deterministic pipeline.
        """
        # ---- PERCEIVE ----
        q_total = quality_scorecard.get("q_total", 0.0)
        mi = quality_scorecard.get("relevance", (0.0, "UNKNOWN"))[0]
        mmd = quality_scorecard.get("distribution_mmd", (0.0, "UNKNOWN"))[0]

        # ---- REASON & ACT (Tool calls) ----
        queries = []
        if q_total < 0.7:
            queries.append("What causes low data quality in nighttime light population estimates?")
        if mi < 0.15:
            queries.append("Why might nighttime lights poorly correlate with population in some regions?")
        if mmd > 0.05:
            queries.append("Distribution shift in nighttime light demographics")
        if not queries:
            queries.append("Validation of nighttime light population models")

        retrieved = []
        for q in queries:
            retrieved.extend(self.rag.query(q, k=2))

        # Deduplicate
        retrieved = list(dict.fromkeys(retrieved))

        # ---- OBSERVE & SYNTHESIZE ----
        report = self._synthesize(
            region_name=region_name,
            predicted_pop=predicted_pop,
            confidence=confidence,
            quality_scorecard=quality_scorecard,
            year=year,
            literature=retrieved,
        )
        return report

    def _synthesize(
        self,
        region_name: str,
        predicted_pop: float,
        confidence: str,
        quality_scorecard: Dict,
        year: int,
        literature: List[str],
    ) -> str:
        lines = [
            f"# Engineering Report: Population Estimate for {region_name}",
            f"**Estimated Year:** {year}",
            f"**Predicted Population:** {predicted_pop:,.0f}",
            f"**Model Confidence:** {confidence}",
            "",
            "## 1. Data Quality Audit",
            f"- **Completeness:** {quality_scorecard['completeness'][1]} ({quality_scorecard['completeness'][0]:.2%})",
            f"- **Consistency:** {quality_scorecard['consistency'][1]}",
            f"- **Accuracy:** {quality_scorecard['accuracy'][1]}",
            f"- **Relevance (MI):** {quality_scorecard['relevance'][1]} (MI = {quality_scorecard['relevance'][0]:.3f})",
            f"- **Distribution Shift (MMD):** {quality_scorecard['distribution_mmd'][1]} (MMD = {quality_scorecard['distribution_mmd'][0]:.4f})",
            f"- **Overall Quality Score (Q_total):** {quality_scorecard['q_total']:.3f}",
            "",
            "## 2. Model Evidence",
            "The estimate was derived from a ResNet-18 CNN regressor trained on aligned nighttime light and WorldPOP 2025 data. "
            "A Grad-CAM heatmap highlights the luminous clusters that most influenced the prediction.",
            "",
            "## 3. Literature Grounding",
        ]
        for i, lit in enumerate(literature, 1):
            # Truncate to ~300 chars for readability
            snippet = lit[:300] + "..." if len(lit) > 300 else lit
            lines.append(f"{i}. {snippet}")

        lines.extend([
            "",
            "## 4. Uncertainty & Caveats",
            "- Population estimates in low-light rural zones carry higher uncertainty due to weak NTL signal.",
            "- Sensor calibration differences across years may introduce bias in backcasted estimates.",
            "- Validation against ground census is recommended before operational use.",
            "",
            "---",
            "*Report generated by the PakLight-Pop Agentic Engine.*",
        ])
        return "\n".join(lines)


if __name__ == "__main__":
    agent = PopulationReportAgent()
    dummy_scorecard = {
        "completeness": (0.98, "PASS"),
        "consistency": (0.95, "PASS"),
        "accuracy": (0.97, "PASS"),
        "relevance": (0.21, "PASS"),
        "distribution_mmd": (0.03, "PASS"),
        "q_total": 0.94,
    }
    report = agent.generate_report(
        region_name="Lahore District, Punjab",
        predicted_pop=13_500_000,
        confidence="High",
        quality_scorecard=dummy_scorecard,
        year=2025,
    )
    print(report)
